spring:
  datasource:
    url: "jdbc:postgresql://127.0.0.1:5432/shortener"
    username: "shortener"
    password: "shortener"
  data:
    redis:
      host: "127.0.0.1"
      port: 6379

shortener:
  base_url: "http://localhost:8080"

logging.level.org.springframework.web.reactive: DEBUG
logging.level.org.springframework.validation: DEBUG
logging.level.org.springframework.boot.autoconfigure.web.reactive.error: DEBUG
