spring:
  application:
    name: "com.michael-petri.shortener"
  main:
    banner-mode: off
    log-startup-info: false
  flyway:
    enabled: true
    baselineOnMigrate: true
    validateOnMigrate: true
    locations: classpath:/db/migration

shortener:
  base_url: "https://michael-petri.com"